[package]
name = "rustcurrent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"                                 # Maelstrom protocol is in JSON
